Add Poseidon syscall
Lightprotocol/solana pull request #1
Opened 2023-04-12 08:32 UTC by vadorovsky

Computing Poseidon[0] hashes is too expensive to be done in a Solana program in one transaction.

This change introduces the `sol_poseidon` syscall which takes two byte sequences as an input and then calculates a Poseidon hash using a BN254 curve and the following Poseidon parameters:

* x^5 S-boxes
* 3 prime fields (one zero prime field and two inputs from the caller)
* 8 full rounds and 57 partial rounds

light-poseidon crate is used here. It has the following benchmark result for calculating a Poseidon hash with 2 inputs:

```
poseidon_bn254_x5_3     time:   [36.076 µs 37.549 µs 38.894 µs]
```

Proposed pricing based on 33ns execution per CU:

37549 ns / 33 (ns per CU) = 1137 CU

[0] https://eprint.iacr.org/2019/458

2023-04-12 23:12 UTC, ananas-block commented
I will test it tmr with my test setup for the syscall

2023-04-13 13:43 UTC, ananas-block requested changes

2023-04-13 13:43 UTC, ananas-block commented on sdk/program/src/poseidon.rs
> +    pub fn hash(vals: &[u8]) -> Result<Hash, PoseidonSyscallError> {
we discussed to remove this right?
(because it doesn't make sense for poseidon since we are always hashing a discrete number of field elements)

2023-04-13 13:43 UTC, ananas-block commented on sdk/program/src/poseidon.rs
> +    pub fn hash(vals: &[u8]) -> Result<Hash, PoseidonSyscallError> {
the way it is now it would only hash take every entry in the &[vals] slice as one element

2023-04-13 22:31 UTC, vadorovsky commented on sdk/program/src/poseidon.rs
> +    pub fn hash(vals: &[u8]) -> Result<Hash, PoseidonSyscallError> {
Good point, fixed

2023-04-14 10:59 UTC, merged